#+TITLE: Daidalos Report für Sprecher:innen

Mit diesem kleinen Programm können Sprecher:innen der Studienstiftung
über Neuaufgenommene informiert werden. Hierzu fragt dich der
Daidalos Report nach deinen Anmeldedaten und das Programm logt sich
für dich ein, navigiert zu deiner Hochschulgruppe und erstellt eine
lokale Kopie von dieser. Diese gleicht das Programm dann ab mit der
vorherigen Kopie und informiert dich dann über Veränderungen.

Im folgenden wird erklärt, wie du dieses Programm installierst und
einstellst. Dabei wird immer mal wieder zwischen Unix-Betriebssystemen
(macOS, Linux) und Windows unterschieden.

* Inhaltsverzeichnis
:PROPERTIES:
:TOC:      :include all :ignore this
:END:
:CONTENTS:
- [[#download][Download]]
  - [[#windows][Windows]]
  - [[#linux-und-macos][Linux und macOs]]
- [[#die-erste-ausführung][Die erste Ausführung]]
- [[#einstellungen][Einstellungen]]
  - [[#anmeldedaten][Anmeldedaten]]
  - [[#browser-und-driver-pfad][Browser und Driver Pfad]]
    - [[#safari][Safari]]
  - [[#hintergrundausführung-und-wartezeit][Hintergrundausführung und Wartezeit]]
- [[#automatische-ausführung-nach-dem-hochfahren][Automatische Ausführung nach dem Hochfahren]]
  - [[#windows][Windows]]
  - [[#linux-und-macos][Linux und macOS]]
  - [[#ubuntu][Ubuntu]]
- [[#fehler-und-anmerkungen][Fehler und Anmerkungen]]
:END:

* Download
** Windows
[[https://github.com/A-dot-S-dot/Daidalos-Report/raw/master/daidalos_report_windows.7z][Hier]] kannst du einen kompriemierten Ordner mit dem Programm
herunterladen. Dieser muss nur noch entpackt werden. Das kann
beispielsweise mit [[https://www.7-zip.org/][7zip]] erfolgen. Für den Download musst du wissen, ob
dein Systemtyp =64-bit x64= oder =32-bit x86= ist. Falls du das nicht
weißt, wird [[https://support.microsoft.com/de-de/windows/32-bit-und-64-bit-windows-h%C3%A4ufig-gestellte-fragen-c6ca9541-8dce-4d48-0415-94a3faa2e13d][hier]] erklärt, wie du das herausfinden kannst.

Ist =7zip= heruntergerladen und installiert, erscheint mit einem
Rechtsklick auf =daidalos_report_windows.zip= den Reiter =7zip= mit dem
dann die gewünschten Entpackungsoptionen ausgewählt werden können.

Anschließend startest du die Anwendung, indem du die Anwendung
=daidalos-report.exe= im entpackten Ordner auswählst.

** Linux und macOs
Das Programm benötigt [[https://www.python.org/][Python]]. Stelle also sicher, dass dieses
installiert ist. Außerdem verwendet das Programm das Paket [[https://www.selenium.dev/][Selenium]]
und [[https://www.qt.io/][PyQt5]]. Du kannst diese installieren, indem du die folgenden Befehl
ins Terminal eingibst.

#+begin_src shell
pip3 install selenium
pip3 install pyqt5
#+end_src

Nun öffne [[https://raw.githubusercontent.com/A-dot-S-dot/Daidalos-Report/master/daidalos_report.py][hier]] die Datei und speichere sie, indem du die Seite
speicherst. Auf Firefox erfolgt dies durch die Tastenkombination
=Ctrl-s=. Das Programm kann nun mit dem folgenden Befehl gestartet
werden.

#+begin_src shell
python3 ~/path/to/daidalos_report.py
#+end_src

Dabei solltest du =/path/to/= durch den tatsächlichen Pfad ersetzen.

* Die erste Ausführung
Vermutlich wird nach dem ersten ausführen der Anwendung eine
Sicherheitswarnung erscheinen. Das liegt daran, dass ich kein
zertifizierter Autor bin. Es sei versichert, dass keine Malware
durch dieses Programm geschleust wird.

Nach dem *ersten* ausführen erscheint ein Dialog mit Einstellungen für
Daidalos Report. Auf diese wird weiter unten eingegangen. Sind alle
Einstellungen vorgenommen worden und sind diese gespeichert, so kann
mit =Report Starten= die Anwendung veranlasst werden eine erste
Untersuchungsroutine durchzuführen. Beim nächsten aufrufen des
Daidalos Report werden die vorgenommenen Einstellungen verwendet, um
vor dem Erscheinen der grafischen Oberfäche eine Untersuchungsroutine
durchzuführen.

* Einstellungen
Nach dem ersten Aufruf von Daidalos Report wird ein Dialog Fenster
geöffnet, in dem du Einstellung vornehmen kannst. Im Folgenden werden
diese erläutert.

** Anmeldedaten
Unter =Benutzername= und =Passwort= können die Anmeldedaten für das
Daidalosnet eingestellt werden. Leider wird das Passwort
unverschlüsselt auf dem Computer gespeichert. Deswegen kann bei
Sicherheitsbedenken, die Einstellung =keine Verschlüsselung=
deaktiviert werden, die dafür sorgt, dass vor jedem Start einer
Untersuchungsroutine nach dem Passwort gefragt wird.

** Browser und Driver Pfad
Daidalos Report unterstützt vier Browser. Nämlich [[https://www.mozilla.org/de/firefox/new/][Firefox]], [[https://www.google.com/intl/de/chrome/][Chrome]],
[[https://www.microsoft.com/en-us/edge][Edge]] und [[https://www.apple.com/de/safari/][Safari]]. Es empfiehlt sich Firefox oder Chrome zu nutzen, da
es bei den anderen Browser anscheinend nicht möglich ist, diese im
Hintergrund aufzurufen (siehe unten).

Damit Daidalos Report mit den jeweiligen Browser interagieren kann
benötigt es zusätzlich Driver. In der folgeden Tabelle sind die
benötigten Driver für die jeweiligen Browser aufgelistet.

| Browser | Driver             |
|---------+--------------------|
| Firefox | [[https://github.com/mozilla/geckodriver/releases][geckodriver]]        |
| Chrome  | [[https://chromedriver.chromium.org/downloads][chromedriver]]       |
| Edge    | [[https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/][msedgedriver]] |
| Safari  | lokal vorhanden    |

Den Safari Fall wird weiter untern behadelt. Bitte lade den passenden
Driver herunter und etpacke ihn. Anschließend kann über die Option
=Driver Path= angegeben werden, wo sich dieser befindet.

*** Safari
/in progress/

** Hintergrundausführung und Wartezeit
Die Einstellung =Hintergrundausführung= lässt die Untersuchungsroutine
im Hintergrunf ablaufen. Die =Wartezeit= gibt an, wie lange der
Daidalos Report zwischen einzelnen Schritten warten soll. Es
empfiehlt sich diese hochzuschrauben, bei langen Ladezeiten.

* Automatische Ausführung nach dem Hochfahren
Eine einfache Möglichkeit Daidalos Report regelmäßig und automatisch
auszuführen ist nach dem Hochfahren. Im folgenden werden die
Einstellungsschritte für die jeweiligen Betriebssysteme aufgelistet.

** Windows
1. Erstelle mit einem Rechtsklick auf =daidalos_report.exe= eine
   Verknüpfung von ebendieser.
2. Drücke =<Windows>= und =R=, gebe "shell:startup" ein und drücke auf
   "OK".
3. Verschiebe die zuvor erstellte Verknüfung in das erschienene
   Fenster und Daidalos Report startet nach jedem hochfahren.

** Linux und macOS
Hierfür kann ein =cronjob= eingerichtet werden. Hierzu kannst du im
Terminal folgendes eingeben.

#+begin_src shell
crontab -e
#+end_src

Anschließend wird ein Dokument geöffnet, in dem du folgeden Zeile am
Ende hinzufügen kannst.

#+begin_src shell
@reboot sleep 60 && DISPLAY=:0 python /path/to/daidalos_report.py > /path/to/daidalos_report.log 2>&1
#+end_src

Hierbei sollte =/path/to= durch den tatsächlichen Pfad ersetzt werden.
Dabei sollte statt =~/= die ausgeschriebene Form =/home/username/=
verwendet werden.

*Anmerkung:* Dieser Cronjob ist so eingerichtet, dass er 60 Sekunden
 nach dem Start wartet, damit das System vollständig geladen ist.
 Außerdem werden Fehlermeldungen in =/path/to/daidalos_report.log=
 gespeichert.

** Ubuntu
Hier könnte eine [[https://help.ubuntu.com/stable/ubuntu-help/startup-applications.html.en][Startup Application]] eingerichtet werden, indem der
folgede Befehl hinzugefügt wird.

#+begin_src shell
python3 /path/to/daidalos_report.py
#+end_src

Dabei sollte =/path/to/= durch den tatsächlichen Pfad ersetzt werden.

* Fehler und Anmerkungen
Ich freue mich sehr über Verbesserungsvorschläge oder über Fehler.
Bitte verwende hierfür den =Issues= Berreich auf Github. Alternativ
schreibe mir gerne eine Mail an [[mailto:alexey.schwarzmann@posteo.de][alexey.schwarzmann@posteo.de]].
